package com.example.lenovo.day04.ui.zhihu.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.day04.ui.zhihu.bean.DailyNewsArticleBean;

import com.example.lenovo.day04.ui.zhihu.dao.DailyNewsArticleBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyNewsArticleBeanDaoConfig;

    private final DailyNewsArticleBeanDao dailyNewsArticleBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyNewsArticleBeanDaoConfig = daoConfigMap.get(DailyNewsArticleBeanDao.class).clone();
        dailyNewsArticleBeanDaoConfig.initIdentityScope(type);

        dailyNewsArticleBeanDao = new DailyNewsArticleBeanDao(dailyNewsArticleBeanDaoConfig, this);

        registerDao(DailyNewsArticleBean.class, dailyNewsArticleBeanDao);
    }
    
    public void clear() {
        dailyNewsArticleBeanDaoConfig.clearIdentityScope();
    }

    public DailyNewsArticleBeanDao getDailyNewsArticleBeanDao() {
        return dailyNewsArticleBeanDao;
    }

}
